### ISSUE TITLE
[sharing] homie-control

### ISSUE THREAD

**Issue by stufisher** [homieiot/homie-esp8266#153]
This isn't an issue as such, just a pointer to a web application i've put together for the homie framework: https://github.com/stufisher/homie-control (some screenshots here: https://github.com/stufisher/homie-control/tree/master/client/screenshots)

Gives you scheduling, profiles, triggers, and history for homie devices. Work ongoing, pretty developer orientated at the moment...

**Comment by benzino77** [comment]
WOW! Screenshots looks pretty nice.
Defenetly I'll check it!

**Comment by marvinroger** [comment]
Awesome, thanks for that! I added your project to the [Community projects](https://homie-esp8266.readme.io/docs/community-projects) page of the docs. Feel free to suggest edits to this page if you want to. 😉

**Comment by gubagu** [comment]
@stufisher Looks great man !

**Comment by stritti** [comment]
I close this issue because the project is already referred within the docs: https://homieiot.github.io/homie-esp8266/docs/stable/others/community-projects/
