### ISSUE TITLE
question: async http server support planned?

### ISSUE THREAD

**Issue by cpan-mila** [homieiot/homie-esp8266#254]
are there plans to support ESPAsyncWebServer with homie? atm this is not possible (it is, but it's more of a hack) because of conflicting definitions ESPAsyncWebServer vs. ESP8266WebServer.

**Comment by marvinroger** [comment]
Ultimately, I plan on using ESPAsyncWebServer rather than the ESPAsyncWebServer. The problem is some features, like the proxy implemented by @flaviostutz would not work anymore. So not short-term, unfortunately.
