### ISSUE TITLE
Wemos D1 mini not autoconnecting

### ISSUE THREAD

**Issue by yborf** [homieiot/homie-esp8266#268]
I'm trying LightOnOff.ino example but I suppose the behavior is the same in other examples. I'm making use of the json configuration file.
Only connection after poweron is successfull. Connections after I reset the D1 mini via the reset button fail. 
Also connection after OTA fails , when D1 mini restarts with the updated fw

Is it a known issue?
If I call WiFi.disconnect() it works properly because json config is forced to be used.
Thank you

**Comment by marvinroger** [comment]
No it's not. What is the output of the serial console?

**Comment by bertmelis** [comment]
I don't see this behaviour on my devices (also Wemos D1 mini).

**Comment by yborf** [comment]
I'm sorry, in the meanwhile I've updated to the latest commit, and I'm not able to replicate the issue.
From my point of view the bug can be removed.
Thank you

**Comment by bertmelis** [comment]
As topic starter you can close the issue yourself.
