### ISSUE TITLE
Attempting to connect to MQTT...

### ISSUE THREAD

**Issue by pwrsoft** [homieiot/homie-esp8266#317]
Node disconnects periodically (every day), after that is stops sending sensor's data.

PS: After manually resetting the device it works as expected.

Here is the console log (after a few hours of beeing disconnected):

в†• Attempting to connect to MQTT...
Retrying (60000ms)...
в†• Attempting to connect to MQTT...
Retrying (60000ms)...
в†• Attempting to connect to MQTT...
Retrying (60000ms)...

**Comment by bertmelis** [comment]
Try pull #314 and set a higher keepalive (300 secs for example).

But even then it's not known why it doesn't reconnect.

**Comment by bertmelis** [comment]
fyi:

Homie.getMqttClient().setKeepAlive(300);

to insert before Homie.setup();

**Comment by marvinroger** [comment]
@pwrsoft have you tried @bertmelis's suggestion?

**Comment by pwrsoft** [comment]
Yes, tried to do the suggestion - unfortunately the issue still happened again a few days ago.

**Comment by marvinroger** [comment]
Can you test with the AsyncMqttClient v0.7.0?

**Comment by stritti** [comment]
Seems to be stale issue.
Will be closed.
Feel free to reopen if there are more information.
