### ISSUE TITLE
Homie 2.0 remains forever waiting for Wi-Fi connection

### ISSUE THREAD

**Issue by cecilios** [homieiot/homie-esp8266#351]
I have a Homie node in operation (boot normal mode) working ok. If I press the RESET button in the ESP8266 the firmware restarts. After the initial debug messages Homie attempts to connect to WiFi but it remains there forever. This is the last debug message:

↕ Attempting to connect to Wi-Fi...

After several hours of investigation I've discovered that if I remove power supply from ESP8266, wait for a couple of minutes and power it up again, now the node works ok. It looks as if Homie get stacked in a wait loop for the wifi connection event, but this event never takes place because the wifi connection still exists (probably, the time required to reset the system is so small than the WiFi station didn't notice that the ESP8266 was disconnected and so the wifi connection was not dropped. And when the ESP8266 asks to connect to wifi it never receives a new connection as it still exists. Not sure if this is the cause but it is the only explanation I have. But I don't know how to fix this behaviour. 

I also have noticed this problem when the node is in operation and I upload a new firmware (direct upload, not using OTA). After the upload is finished, ESP8266 automatically restarts and the new firmware is executed (boot normal mode). Homie attempts to connect to WiFi but it remains there forever. And the only solution is to remove power supply for a couple of minutes.

I'm using Homie 2.0 from development repo.

**Comment by bertmelis** [comment]
I believe it's a bug in the Arduino framework. Power cycling the device solves the issue. Can't find the issue though...

**Comment by cecilios** [comment]
For now I have bypassed the problem by forcing a wifi disconnection

        `WiFi.disconnect();`

in my node setup when not in config mode

**Comment by marvinroger** [comment]
I'll take a look!

**Comment by johnjore** [comment]
For what it's worth, I've seen the same issue when working on a reed sensor, frequent connect / disconnect. The code here didn't have the same problem, https://github.com/8n1/ESP8266-Tiny-Door-and-Window-Sensor.

**Comment by andreasbrinch** [comment]
I have the same issue, but only when I have a static ip configured. It cant connect after a reset (using the button on wemos) or after deep sleep. Everything works when the static ip is not configured and after a power off.

**Comment by andreasbrinch** [comment]
And I dont think it is related to the time the device is off. I can repower the device with only a second in delay which works and it doesn't with a reset of 2-3 seconds.

**Comment by highno** [comment]
I can confirm this bug (tho I can't exactly see, what the sketches changes were that led to this bug).
In my case the workaround from cecilios did the trick, which leads me to the same idea. Maybe there are changes in Arduino, the ESP-core or it may be hardware-dependent, but it really seems, as if homie looks for a special event for wifi connections and does not poll the wifi connection state. 

WiFi.status() returns 3 (= WL_CONNECTED) so everything else is working correctly. 

Maybe there should be a regular polling of the wifi state in Homie's loop if Homie thinks there is no connection?

**Comment by stritti** [comment]
I noticed that problem also using current ‘develop-v3‘ branch

**Comment by stritti** [comment]
Doing some "serial print debugging" I found, that `void BootNormal::_wifiConnect()`is completely done. It must be in superordinate caller.

**Comment by stritti** [comment]
> For now I have bypassed the problem by forcing a wifi disconnection
> 
> ```
>     `WiFi.disconnect();`
> ```
> in my node setup when not in config mode

works still on develop-v3 as workaround.

**Comment by bodiroga** [comment]
> works still on develop-v3 as workaround.

Should we create a PR to add it?

**Comment by stritti** [comment]
I created a PR.

**Comment by stritti** [comment]
Further input for this issue:
* https://www.youtube.com/watch?v=OGpIy0-ewvE&lc=UgzHlFH-lhwvSbQwWdF4AaABAg
* https://github.com/esp8266/Arduino/issues/5527

**Comment by stritti** [comment]
Workaround with `WiFi.disconnect();` within setup applied to branches:
- develop-v3
- develop

I leave the issue open for further investigations of root causes.
