### ISSUE TITLE
READY_TO_SLEEP fires prematurely

### ISSUE THREAD

**Issue by haimgel** [homieiot/homie-esp8266#368]
I'm following the docs to go into the deep sleep. However, when HomieEventType::READY_TO_SLEEP event is being generated, it seems to me that the MQTT client is not cleanly disconnected yet. I'm looking a the network trace, and the TCP connection is being left open when the device goes to sleep (when I call ESP.deepSleep(secs) as a response to HomieEventType::READY_TO_SLEEP). 

If I just set a flag when handling the event, and call ESP.deepSleep from the main loop, 100ms later, I can see TCP connection being closed properly.

**Comment by marvinroger** [comment]
Indeed, we don't wait for the ACK before firing the event.

**Comment by stritti** [comment]
Seems to be stale issue.
Will be closed.
Feel free to reopen if there are more information.
