### ISSUE TITLE
Can't connect to Configurator

### ISSUE THREAD

**Issue by lnrobby** [homieiot/homie-esp8266#376]
Installed Homie 2 
Loaded the basic script onto a WEMOS D1 R2 
The serial console shows that it is in configuration mode.

⸮⸮⸮⸮⸮WeMos
✖ /homie/config.json doesn't exist
Configuration invalid. Using CONFIG MODE
💡 Firmware LenWater (1.0.0)
🔌 Booting into config mode 🔌
Device ID is a020a6194836
AP started as Homie-a020a6194836 with IP 192.168.123.1

Connected to the network on my Android V7
Ran up Homie Setup on my android
Just get "Waiting for device".

Have zapped the device again and tried again, still exactly the same.
Have back levelled the libraries to make sure they are on the minimum requirements for Homie 2.0.0 
Still the same

![rps20170727_123738_833](https://user-images.githubusercontent.com/7725765/28668783-6b274922-72c9-11e7-940d-da1eb85103c3.jpg)
![rps20170727_123450_411](https://user-images.githubusercontent.com/7725765/28668803-81be95c8-72c9-11e7-9a33-8c89a7b26d83.jpg)
![rps20170727_123707_859](https://user-images.githubusercontent.com/7725765/28668823-956841b4-72c9-11e7-9fc3-bd5d8c414f2a.jpg)

**Comment by luebbe** [comment]
Waiting for the device can take more than a minute. How long did you wait?

**Comment by lnrobby** [comment]
Over 10 minutes for the first attempt. Since then numerous attempts form 1 minute to 8 hours.

**Comment by luebbe** [comment]
That should be long enough :)
with my devices I see different messages in the serial console, when something is connecting to the AP. 
Normally just "scanning for networks" repeatedly.

**Comment by lnrobby** [comment]
I have since tried it on a WEMOS D1 Mini Pro. exactly the same situation.

**Comment by marvinroger** [comment]
What browser do you use? Which OS? Also, is the configurator loaded over
HTTPS?

**Comment by lnrobby** [comment]
Trying to connect to the Wemos to configure it using your app on an LG G5 running android Nougat (Homie Set Up Your Device).  Interestingly in V2 the device is not asking for a password when connecting through the android. I don't know where I find your setup-build for V2 to run as a web app.

I am now seeing a problem just trying to connect to the wifi AP in Nougat as it is saying "Obtaining IP Address" and then stops the connection. Again I have tried zapping and rebuilding it but no success.

**Comment by lnrobby** [comment]
Tried yet again by completely zapping the device. Got as far as running an empty homie script and it says in Config mode. Connected via my Android and tried the app again . Nothing. Tried connecting to 192.168.123.1 and it said http://192.168.123.1/ is unreachable

**Comment by jesserockz** [comment]
Try turning off your mobile data, Android will most of the time try to route all connections through that if the wifi has no internet access.

**Comment by lnrobby** [comment]
Tried turning off mobile data. Still no difference

**Comment by luebbe** [comment]
I could connect with browsers on mobile devices (iOS and Android) but had trouble entering or saving the configuration to the device.
Currently I use an old laptop (lubuntu, firefox) for the first time configuration of a homie device. Still needs some time to connect, but works reliably.

**Comment by lnrobby** [comment]
I will try that. I wonder what part of this is going wrong.

On 28 Jul 2017 12:00, "luebbe" <notifications@github.com> wrote:

I could connect with browsers on mobile devices (iOS and Android) but had
trouble entering or saving the configuration to the device.
Currently I use an old laptop (lubuntu, firefox) for the first time
configuration of a homie device. Still needs some time to connect, but
works reliably.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/marvinroger/homie-esp8266/issues/376#issuecomment-318624100>,
or mute the thread

**Comment by lnrobby** [comment]
I have since set up this example from sparkfun https://learn.sparkfun.com/tutorials/esp8266-thing-hookup-guide/example-sketch-ap-web-server. It immediately connects and can talk to the AP so logic suggests that  there must be something stopping it in Homie or one of the libraries I would guess.

**Comment by raliand** [comment]
The error is:
XMLHttpRequest cannot load http://192.168.123.1/heart. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://setup.homie-esp8266.marvinroger.fr' is therefore not allowed access.

**Comment by lnrobby** [comment]
This is now getting even more confusing. Since I tried the Sparkfun example I have been able to successfully launch the V1.5 Homie configurator via the web on oth devices that were not working. This kind of suggests that something was missing in the Homie build but the Sparkfun test sorted it out. I know this doesn't really make much sense as I thought the build when loaded onto the 8266 it cleared all the original stuff out.

**Comment by sirvaulterscoff** [comment]
The same issue for me. Had working prototype built with homie on Wemos D1mini.
Then i decided to update configuration of device, so i've sent a message to $implementation/reset endpoint.

After that i've had my device booting in configuration mode. But after AP appears i can't connect to it. Tried both mac and iphone, none of them connects. Tried erasing flash and using different sketches - no luck.

Is there a way to configure homie properties from the code itself?

**Comment by raliand** [comment]
I found a chrome extension that did it for me: https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi

**Comment by benzino77** [comment]
You can always upload new SPIFFS image with new config.json via Arduino IDE/Platformio.

**Comment by luebbe** [comment]
The quickest way for me to send the config to a device in configuration mode is to upload config.json via curl. But that means that your PC/Laptop has to be connected to the homie AP first

**Comment by sirvaulterscoff** [comment]
@benzino77 thanks for you feedback. Never done this before, are there any guides on uploading config.json to esp ?

**Comment by benzino77** [comment]
I'm using Platformio:
![github1](https://user-images.githubusercontent.com/15658235/29270316-813e6bc4-80f6-11e7-93bd-0d30093328e1.PNG)

![github2](https://user-images.githubusercontent.com/15658235/29270320-85dd6bb2-80f6-11e7-8826-de4329b67382.PNG)

**Comment by roidayan** [comment]
I also were unable to connect with the default ui_bundle.
I tried chrome/FF/IE11.

In IE11 there is an error Promise is undefined. need to add js to implement Promise if doesn't exists by the browser.

In chrome I got an error about missing js/css so I looked in the ui_bundle file and saw this:
```
<link href="./client.7178b4b2.js" rel="preload">
<link href="./client.9f23c3ce.css" rel="preload">
<link href="./vendor.0f6f9a63.js" rel="preload">
<link href="./manifest.2fe231a1.js" rel="preload">
```

I removed it as those do not exists really. they are inlined in the html already.
After removing this chrome worked fine without an issue.

**Comment by marvinroger** [comment]
@roidayan I just fixed that "preload" issue for the latest bundle. 😉

**Comment by roidayan** [comment]
Great thanks :-)

**Comment by ortegafernando** [comment]
is this fixed? I can't setup Wemos D1 mini with Homie..

**Comment by luebbe** [comment]
I always "push" my config.json with curl. It's a lot quicker to edit the config in a normal editor and cal a bat/bash script that uploads it.
The configurator is too slow for me and it is not consistent at some places.

**Comment by timpur** [comment]
@luebbe if its not consistent then lets work on fixing that !! Any issues ?

**Comment by luebbe** [comment]
Strange, I'm pretty sure that I submitted issues or commented on issues, but I can't find them.
From the top of my head:
- It didn't work with all browsers. FF on Linux was ok, chrome on android too, chrome on iOS not
- You can't enter a zero value in the configurator. 0 doesn't work, but 0.01 is accepted
- And another problem with entering values which I can't remember right now.

Admittedly I haven't used the web configurator for some months because I got fed up.

**Comment by timpur** [comment]
okay well im going to be doing alot of work to fix these issues soon when im finished for the year :)

**Comment by tripflex** [comment]
TBH I think majority of these issues should have been resolved by the CORS fix...

With that said though, Android Lollipop or newer, if wifi does not have internet it will not route any traffic through wifi (I can 100% confirm this on Android Oreo 8+) which has created a whole ton of fun for me regarding Cordova Wifiwizard plugin I forked https://github.com/tripflex/WifiWizard2/issues/7 

... even if you're attempting to connect to a PRIVATE IP address in PRIVATE IP range, on a network that *should* have a route already set when connecting to that wifi ... blehhh mehhhh rawrr

> Android's Marshmallow operating system introduced a non-forward compatible change that causes network traffic to sometimes use cellular data instead of WiFi when connected to a WiFi access point that cannot reach Google's servers. This is problematic for applications that need to talk to local devices on that access point (i.e., anything in the 10.0.0.0/8 or 192.168.0.0/16 ranges). 

Also, Promises have been around for a while now, so majority of browser versions 2014 or newer should support them (https://caniuse.com/#feat=promises)

Unless you're using Internet Exploder which ... you really shouldn't be using anyways ... but yeah I guess the config ui could have a promises polyfill included to be compatible with shatty browsers

**Comment by stritti** [comment]
No progress on this issue. We will close.
