### ISSUE TITLE
Homie 2.0.0 beta.1 requires git client

### ISSUE THREAD

**Issue by neilbrookins** [homieiot/homie-esp8266#388]
I'm using PlatformIO on the Atom text editor with Windows 10 and Homie 2.0.0-beta.1
I'm following the instructions on the quickstart/getting-started guide, which state:
"...add this in your platformio.ini:
lib_deps = git+https://github.com/marvinroger/homie-esp8266.git#develop"

I did exactly as I was instructed and it caused Atom/PlatformIO to get stuck in an infinite loop that printed again and again the same error that "git" was not installed.  As a newbie user I didn't know what to do at the time. After much time researching, it turns out all I needed to do was install "git" with all the default settings and the error was resolved.

Can you please update the web page at: 
http://marvinroger.github.io/homie-esp8266/2.0.0-beta.1/quickstart/getting-started/

to include a statement such as the following:
Before editing platformio.ini as shown below, you must install "git" if you don't already have it. For Windows, just go to http://git-scm.com/download/win and the download will start automatically. 
Note, this is only a requirement for the beta, not the final release.

**Comment by euphi** [comment]
Oh, it should also be possible to use the _v2.0.0-beta.1_ tag:

`lib_deps = git+https://github.com/marvinroger/homie-esp8266.git#v2.0.0-beta.1`

@marvinroger I think its better to use this "tag-variant" for the `lib_deps` with platformio.
