### ISSUE TITLE
Renewing SSL certificate

### ISSUE THREAD

**Issue by sirvaulterscoff** [homieiot/homie-esp8266#399]
Hello,

i've got a question, which is not covered by current documentation. Let's say im using self-signed certificate with short-term validity - 2 month - for my homie-mqtt communication. Once certificate expires and should be renewed how am i supposed to update all my homie devices with new fingerprint ?

**Comment by timpur** [comment]
Good point, i like, might add this to homie config file, thus you can just send incremental json to update it.
Will also implement homie ssl mode so its also easier to enable ssl.

**Comment by timpur** [comment]
Has been added

**Comment by stritti** [comment]
It is merged into `develop-v3`
