### ISSUE TITLE
BSSID / Channel doesn't seem to work

### ISSUE THREAD

**Issue by x821938** [homieiot/homie-esp8266#404]
When I try to add BSSID and channel to my config.json like this

    "bssid": "DE:AD:BE:EF:BA:BE",
    "channel": 1,

I can't connect to my wifi. I am pretty sure about my BSSID and channel.
I only get this:

```
↕ Attempting to connect to Wi-Fi...
2017-09-26 14:08:15	Message	✖ Wi-Fi disconnected
Triggering WIFI_DISCONNECTED event...
2017-09-26 14:08:15	Message	↕ Attempting to connect to Wi-Fi...
2017-09-26 14:08:17	Message	✖ Wi-Fi disconnected
Triggering WIFI_DISCONNECTED event...
↕ Attempting to connect to Wi-Fi...
2017-09-26 14:08:19	Message	✖ Wi-Fi disconnected
Triggering WIFI_DISCONNECTED event...
↕ Attempting to connect to Wi-Fi...
```

I am using the latest development version of Homie. 

If I remove the two lines of config it connects very fast. But I want to connect even faster for a Homie-battery project I am working on.

**Comment by timpur** [comment]
still having this issue?

**Comment by x821938** [comment]
I made my own solution, so I havn't really checked.
If you havn't changed to code, I will still have the problem. I tried on 3 different nodemcu's

Best regards,
   Alex

**Comment by timpur** [comment]
Okay I'll test it out and fix if there is still an issue.

**Comment by tripflex** [comment]
@x821938 did you try this with debug output enabled? I only see homie specific logging ...  just add this in setup `Serial.setDebugOutput(true);` and you should get more specific information from actual wifi connection in console

**Comment by stritti** [comment]
Closing because of no more response.
