### ISSUE TITLE
Helpers.cpp:265:47: error: 'MAX_OTA_PATH_LENGTH' was not declared in this scope

### ISSUE THREAD

**Issue by snowboarder04** [homieiot/homie-esp8266#406]
Hey,

I'm trying to build the example [minimum requirement code](http://marvinroger.github.io/homie-esp8266/stable/2.-Getting-started/#bare-minimum-sketch) to get things started and I'm using the most [recent pull](https://github.com/marvinroger/homie-esp8266/commit/d4d48e09acf8fa6d8309b3a52e9af9aa29ac200d_).

I get the below error when attempting to compile:

`\src\Homie\Helpers.cpp: In static member function 'static HomieInternals::ConfigValidationResult HomieInternals::Helpers::_validateConfigOta(const ArduinoJson::JsonObject&)':

\src\Homie\Helpers.cpp:265:47: error: 'MAX_OTA_PATH_LENGTH' was not declared in this scope

       if (strlen(object["ota"]["path"]) + 1 > MAX_OTA_PATH_LENGTH) {`

**Comment by timpur** [comment]
More Info Needed (version, dev?) still got this issue ?
