### ISSUE TITLE
Question: datalogger without wifi

### ISSUE THREAD

**Issue by taiuti** [homieiot/homie-esp8266#504]
Hello to all,
I'm using homie-esp8266 as datalogger. If the wifi is turned off is it possible to save the data on SPIFFS or SD card and send them when the wifi is active again?
Thanks,
Marco

**Comment by stritti** [comment]
I think you could do this by using the new feature to run loops although Homie is not connected to MQTT.

See PR https://github.com/homieiot/homie-esp8266/pull/490
