### ISSUE TITLE
Crash on MQTT Subscription with H801

### ISSUE THREAD

**Issue by Zero545** [homieiot/homie-esp8266#517]
Hi,

I'm just starting to set up an LED strip controller with the H801. I really wanted to use the Homie framework since it seemed quite well developed.

Unfortunatly I had some issues with the minimum example. Which I also have found a solution for (I hope it's valid).
 I got the example to start on my H801 in the following way, but it kept crashing:

```
#include <Homie.h>

void setup() {
  Serial1.begin(115200);
  Serial1 << endl << endl;
  pinMode(5, OUTPUT);
  
  Homie.disableResetTrigger();
  Homie.setLedPin(5, LOW);
  Homie.setLoggingPrinter(&Serial1);
  
  Homie_setFirmware("bare-minimum", "1.0.0"); // The underscore is not a typo! See Magic bytes
  Homie.setup();
}

void loop() {
  Homie.loop();
}
```
I narrowed down the the issue to a single line in BootNormal.cpp (in 
void BootNormal::_advertise()):

`packetId = Interface::get().getMqttClient().subscribe(_prefixMqttTopic(PSTR("/$implementation/ota/firmware/+")), 1);`

Here is the log of the crash:

```
1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld

SDK:2.2.1(cfd48f3)/Core:2.4.1/lwIP:2.0.3(STABLE-2_0_3_RELEASE/glue:arduino-2.4.1)


💡 Firmware bare-minimum (1.0.0)
🔌 Booting into normal mode 🔌
{} Stored configuration
  • Hardware device ID: 6001946f9420
  • Device ID: led-strip-kitchen
  • Name: Kitchen LED
  • Device Stats Interval: 60 sec
  • Wi-Fi: 
    ◦ SSID: edesteil
    ◦ Password not shown
  • MQTT: 
    ◦ Host: 192.168.0.39
    ◦ Port: 1883
    ◦ Base topic: homie/
    ◦ Auth? yes
    ◦ Username: eweis
    ◦ Password not shown
  • OTA: 
    ◦ Enabled? yes
↕ Attempting to connect to Wi-Fi...
bcn 0
del if1
usl
mode : sta(60:01:94:6f:94:20)
add if0
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 5
cnt 

connected with edesteil, channel 1
dhcp client start...
ip:192.168.0.248,mask:255.255.255.0,gw:192.168.0.1
✔ Wi-Fi connected, IP: 192.168.0.248
Triggering WIFI_CONNECTED event...
↕ Attempting to connect to MQTT...
Sending initial information...

 ets Jan  8 2013,rst cause:4, boot mode:(1,7)

wdt reset
```

After changing the line:

`  size_t longestSubtopicLength = 29 + 1;  // /$implementation/ota/firmware`

to:

`  size_t longestSubtopicLength = 31 + 1;  // /$implementation/ota/firmware/+`

everything seems to work fine. Can someone please confirm that this makes sense?

**Comment by Zero545** [comment]
@luebbe: Thank you for sharing. Your project helped me a lot for my first RGB controller implementation.

**Comment by stritti** [comment]
Could this issue be closed? Please confirm.

**Comment by Zero545** [comment]
No, it seems the code I mentioned is still the same and probably the problem is also not fixed. But I did not test it again.

**Comment by codefrey** [comment]
I created a PR for the MQTT buffer size calculation error pointed out by @Zero545 (see #633).

**Comment by stritti** [comment]
PR is merged.

**Comment by luebbe** [comment]
Closing, since the PR is merged
