### ISSUE TITLE
Reboot instead Reset

### ISSUE THREAD

**Issue by marcolino7** [homieiot/homie-esp8266#556]
Hi,
I am using version 2.0.0 and all of my board based on ESP8266 have one button. I would like to use this button to reboot board instead reset. Button should have 2 function. Short press, toggle a relè, long press reboot, not reset the board. Is it possible?

Thanks

**Comment by luebbe** [comment]
Yes, you have to turn the default behaviour (Reset) off in Homie and implement your own button handler.
