### ISSUE TITLE
if MQTT server goes down, the Homie devices stop responding to physical keys

### ISSUE THREAD

**Issue by manuelmouraguedes** [homieiot/homie-esp8266#571]
Hi, 

Just implemented Homie on a Tuya based wall switch (2 buttons). Connects to Mosquitto under HASSIO and everything is working great.
BUT, if I stop the MQTT server the physical buttons stop responding and any rebbot hangs with the repeating  debug message "Attempting to connect to MQTT..."
So, if MQTT is down the switch cannot perform is offline capabilities, i.e react to physical button press and trigger relay
I intend to replace all my wall switches by these Homie/Tuya ones. Cannot have the wall switches dead if the Wifi or Mosquitto goes down...
Is this how Homie works, requiring that MQTT will always be available to respond or is there a confuguration that enables the switch to communicate with MQTT when available but still work offline when MQTT is not reachable?

Thanks,

**Comment by euphi** [comment]
The loop handler is not called, if MQTT is disconnected.

This was already discussed earlier. For version 2 there is a PR that has not yet been merged: #490. You can manually add it to your sources.

For version 3 I will provide a PR soon (and also care for tests).

**Comment by euphi** [comment]
Closed with #490.
