### ISSUE TITLE
[develop-v3] Build error in Branch develop-v3

### ISSUE THREAD

**Issue by stritti** [homieiot/homie-esp8266#573]
The current version in branch 'develop-v3' can not be compiled. There is following error:

```
.piolibdeps\Homie\src\Homie\Config.cpp: In member function 'bool HomieInternals::Config::_spiffsBegin()':
.piolibdeps\Homie\src\Homie\Config.cpp:13:37: error: no matching function for call to 'fs::FS::begin(bool)'
_spiffsBegan = SPIFFS.begin(true);
^
```
see: 
https://github.com/homieiot/homie-esp8266/blob/5b34a624950f533bf85b42efad1158bed7823caf/src/Homie/Config.cpp#L13

I used current `espressif8266 @ 2.0.4`  to compile project and following platformio.ini:
```
platform = espressif8266
board = nodemcuv2
framework = arduino

;Add the PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY build flag to ensure reliable OTA updates.
build_flags = -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

lib_deps =
  https://github.com/homieiot/homie-esp8266.git#develop-v3
```

**Comment by stritti** [comment]
See also at Travis-Build of my example: https://travis-ci.org/stritti/Homie8266-Ping

**Comment by stritti** [comment]
I think it is caused by merging ESP32 PR:
https://github.com/bodiroga/homie-esp8266/pull/1#issuecomment-454373132

**Comment by stritti** [comment]
PR created.

**Comment by euphi** [comment]
PR merged. Many thanks!
