### ISSUE TITLE
[develop-v3] Password for MQTT broker too long

### ISSUE THREAD

**Issue by EinfachArne** [homieiot/homie-esp8266#586]
Hey,

today I tried to run the current development version of Homie-V3 on a Wemos Lolin32 V1.0.0 and everything was fine until I tried to upload a config via HTTP JSON API.

The response was: 
```
400 Bad Request (application/json): 
mqtt.password too long.
```
The password I tried to use is 36 characters long. Is there a reason for the limit and can it be changed?

**Comment by euphi** [comment]
See `/src/Homie/Limits.hpp` - maximum PW length is 32 Byte (+1Byte 0-terminator).
You can change the file locally to allow longer passwords.
