### ISSUE TITLE
[develop-v3] ota_updater not working, missing $online topic

### ISSUE THREAD

**Issue by BasvanH** [homieiot/homie-esp8266#589]
Hello,

I'm trying to ota to a develop-v3 running esp8266. The ota_updater script is stuck on "Waiting for device to come online...". Looking at the code it's waiting for the $online topic, which I do not see coming from the home v3 device.

I'm certain I have the correct base topic & device id as I see all kinds of other messages coming by, just not the $online.

ota is enabled via json config. Confimed with $implementation/config .

Regards,
Bastiaan

**Comment by euphi** [comment]
I changed the $online topic to $state, see 83cf3acca108ade2a741507f264d2d18691758f9

Now OTA works, however the python scripts seems to compare the old checksum instead of the correct new one?!

Furthermore, the esp8266 crashes after OTA, but comes up again after WDT timeout with correct new firmware.

**Comment by BasvanH** [comment]
Using the $state topic works. I do not have the problems with the checksum, it validates correctly.

**Comment by euphi** [comment]
It seems that the update scripts receives the old checksum again after the `$state` changes to `init`, altough the esp only sends the new checksum after restart. (checked with mosquitto_sub).

There seems to be a retained message with the old checksum, however, I do not understand why the updater-script receives it again.
I can see that the same issue happens with the firmware version.

**Comment by bertmelis** [comment]
> It seems that the update scripts receives the old checksum again after the `$state` changes to `init`, altough the esp only sends the new checksum after restart. (checked with mosquitto_sub).

Same here. Using Python 2.7.13
Although the device has updated successfully, the script indicates it has failed.

**Comment by euphi** [comment]
Oh. I don't remember this issue, although I even changed something on the script for it...
Two important remarks:

* The update script shall allow both `$online` or `$state` for starting OTA - so it also possible to use OTA for update from 2.0 to 3.x

* The "wrong checksum" bug is still present, so it needs to be fixed.
