### ISSUE TITLE
Wiki: make editable for everybody

### ISSUE THREAD

**Issue by stritti** [homieiot/homie-esp8266#596]
I think Wiki should be maintainable for everybody to get more flexibility and be more close to community.

**Comment by kleini** [comment]
Is it possible to integrate a review by contributors before changes are published? There are maybe some trolls out there, trying to destroy things, although I hope, this will not be the case.

**Comment by stritti** [comment]
You need at least a GitHub account. So not really everyone... I think reviews are not required if I have a look at other projects.

**Comment by luebbe** [comment]
according to the gitter chat there was only one person interested in editing wiki pages. Why don't we just make this person a contributor?

**Comment by stritti** [comment]
Hm, I think it could be another level to contribute without being contributor.

**Comment by stritti** [comment]
Close issue: less feedback, would not be changed.
