### ISSUE TITLE
Homie doesn't reconnect using latest async-mqtt-client

### ISSUE THREAD

**Issue by bertmelis** [homieiot/homie-esp8266#599]
using:
- esp32 (lolin32)
- develop-v3 branch
- latest stable Arduino (built using platformio)

I updated to latest async-mqtt-client, now my esp32 shows up as `lost`. I haven't looked into the cause yet, but I my first suspects are the mutexes introduced in the mqtt library.

**Comment by MoJo2600** [comment]
I think, this issue is related: #529
