### ISSUE TITLE
Disable config mqtt announcement?

### ISSUE THREAD

**Issue by jimtng** [homieiot/homie-esp8266#604]
I'm using homie-esp8266 v2.0

I am using HomieSetting to store some sensitive data (e.g. access code, password, pin, etc). Each time the esp8266 comes online / reset, it would send the $implementation/config json data to MQTT, thus revealing this sensitive data, not to mention that this is also a retained message.

Is there a way to suppress this, perhaps in a similar manner to the suppression of wifi password in the config message?

**Comment by kleini** [comment]
Currently there is no way to suppress the HomieSetting values to be printed as part of the configuration message. But this is software and this can be implemented.
