### ISSUE TITLE
[develop-v3] Incremental Configuration for custom Settings

### ISSUE THREAD

**Issue by MajorTwip** [homieiot/homie-esp8266#605]
When sending an incremental configuration for custom settings, following error is logged:
Object settings missing.
 
Sample:
{"settings" :{
 "percentage" :75
}
}
to homie/device-id/$implementation/configuration/set

This limitation is known and marked as ToDo in sourcecode.

**Comment by codefrey** [comment]
Should be fixed since merging #653. Please close.
