### ISSUE TITLE
developer v3 - globalInputHandler

### ISSUE THREAD

**Issue by haesslo** [homieiot/homie-esp8266#608]
It seems that this was changed from
bool globalInputHandler(const HomieNode& node, const String& property, const HomieRange& range, const String& value)
to:
bool globalInputHandler(const HomieNode& node, const HomieRange& range, const String& property, const String& value)

...took me a while of digging to find out... maybe to update the V3 documentation:
https://homieiot.github.io/homie-esp8266/docs/develop-v3/advanced-usage/input-handlers/

Cheers

**Comment by stritti** [comment]
Doc is fixed. Many thanks for reporting.
Sorry for the long delay for that simple issue.
