### ISSUE TITLE
Programming a sonoff dual R2 : not working anymore for me..

### ISSUE THREAD

**Issue by mosseb** [homieiot/homie-esp8266#614]
Hi.
With my friend we built our own firmware for sonoff dual r2 using homie.
It has been working for a lot of sonoffs, then I needed to program a new one recently and could not make it work. There has been no change in source code since.
I'm not sure if it's atom related (new version?) or platformio related (new version?) or hardware related (new version of the sonoff ?).
Anyway, I'm not really sure where to post for help because I don't think it's homie related.
Could you point out for some useful resources like forums where to get help ?
Thank you.

**Comment by amayii0** [comment]
Hi,
First thing, please define "not working" and also if anything already "works".

**Comment by mosseb** [comment]
Erm.. While I started again reproducing the issue for exmplanation, this suddenly fell to working state..
Well sorry for the annoyance...
I suppose I must be happy now :)
Thanks anyway !
