### ISSUE TITLE
[develop-v3] Update links to example sketches for v3 

### ISSUE THREAD

**Issue by CWempe** [homieiot/homie-esp8266#638]
I noticed the example sketeches in the documentation for v3 still link to the `develop` branch. Not `develop-v3`.

https://github.com/homieiot/homie-esp8266/blob/develop-v3/docs/quickstart/getting-started.md

Maybe they could be defined relative to the selected branch.

**Comment by stritti** [comment]
It is linked always to the default branch. Refactoring the repository removed now develop-v3 and develop is default.
