### ISSUE TITLE
Homie.doDeepSleep; time_us in uint64_t 

### ISSUE THREAD

**Issue by sude22** [homieiot/homie-esp8266#652]
Hi,
just found [here](https://thingpulse.com/max-deep-sleep-for-esp8266/) that the datatype for the deepsleep parameter changed to uint64_t with ESP8266 Arduino core 2.4.1.

Shouldn't the Homie.doDeepSleep method's parameter also be uint64_t to enable longer sleep durations than 71min?

Regards

**Comment by sude22** [comment]
I created a PR...

**Comment by bodiroga** [comment]
Thanks @sude22! :+1:

**Comment by stritti** [comment]
https://github.com/homieiot/homie-esp8266/pull/656
